### ISSUE TITLE
Package renamed, but readme not updated

### ISSUE THREAD

**Issue by bmoscon** [manahl/hubot-servicenow-tickets#2]
renamed hubot-servicenow-tickets, but various spots in the readme still reference hubot-servicenow

**Comment by bmoscon** [comment]
@Wilfred if the rest of the instances where hubot-servicenow look correct, feel free to close this

**Comment by Wilfred** [comment]
Thanks.

**Comment by bmoscon** [comment]
thanks wilfred. I would have changed them all, but I wasnt sure if ONLY the package named changed or if everything else did as well.
